# Generated by Django 5.0.3 on 2024-03-24 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tours',
            options={'verbose_name': 'Tours', 'verbose_name_plural': 'Tours'},
        ),
    ]
